# Generated by Django 5.0 on 2024-03-18 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_userspost_status_alter_post_content_alter_post_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userspost',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
