# Generated by Django 5.0 on 2023-12-14 08:52

import django_google_maps.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_location_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='geolocation',
            field=django_google_maps.fields.GeoLocationField(max_length=100),
        ),
    ]
