# Generated by Django 5.0 on 2023-12-19 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_location_geolocation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['created_on']},
        ),
        migrations.AddField(
            model_name='comments',
            name='created_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
