# Generated by Django 5.0 on 2023-12-20 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_userspost_author_userspost_featured_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userspost',
            options={'ordering': ['created_on']},
        ),
    ]
