# Generated by Django 5.0 on 2023-12-23 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_userspost_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.AddField(
            model_name='userspost',
            name='slug',
            field=models.SlugField(default='', max_length=100, unique=True),
        ),
    ]
